name: CI
on:
  - push
  - pull_request
jobs:
  nix-build:
    name: Nix build
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-beta, macos-latest]
        include:
          - os: ubuntu-beta
            system: x86_64-linux
          - os: macos-latest
            system: x86_64-darwin
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
            accept-flake-config = true
            log-lines = 50
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: ✅ Check
        run: nix flake check --impure
      - name: 🐚 Build Shell
        run: nix build -L '.#devShells.${{ matrix.system }}.default' --impure
      - name: 📦 Build Package
        run: nix build -L '.#packages.${{ matrix.system }}.default' --impure
      - uses: nick-fields/retry@v2 # Sad workaround for terraform error Error 403: Permission 'run.operations.get' denied on resource
        name: 🚛 Build Container
        if: ${{ matrix.system == 'x86_64-linux' }}
        env:
          GOOGLE_CREDENTIALS_BASE64: ${{ secrets.GCLOUD_GITHUB_ACTIONS_SA }}
        with:
          max_attempts: 2
          retry_wait_seconds: 5
          command: |
            export GOOGLE_CREDENTIALS=$(echo "$GOOGLE_CREDENTIALS_BASE64" | base64 -d)
            nix run -L .#container-xhaskell-x86_64-linux.deployGceCloudRun --impure -- apply -auto-approve
