name: CI
on:
  - push
  - pull_request
jobs:
  nix-build:
    name: Nix build
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-beta, macos-latest-xlarge]
        include:
          - os: ubuntu-beta
            system: x86_64-linux
          - os: macos-latest-xlarge
            system: aarch64-darwin
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: ✅ Check
        run: nix flake check --impure --accept-flake-config
      - name: 🐚 Build Shell
        run: nix build -L '.#devShells.${{ matrix.system }}.default' --impure --accept-flake-config
      - name: 📦 Build Package
        run: nix build -L '.#packages.${{ matrix.system }}.default' --impure --accept-flake-config
      - name: 🚛 Build Container
        run: |
          nix develop . --impure --accept-flake-config
          echo "${{ vars.GCLOUD_GITHUB_ACTIONS_SA }}" | jq .project_id
          echo "${{ vars.GCLOUD_GITHUB_ACTIONS_SA }}" | skopeo login -u _json_key --password-stdin "europe-west3-docker.pkg.dev"
          nix build -L '.#packages.${{ matrix.system }}.container-xhaskell-x86_64-linux.copyToRegistry' --impure --accept-flake-config
