name: CI
on:
  - push
  - pull_request
jobs:
  nix-build:
    name: Nix build
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-beta, macos-latest]
        include:
          - os: ubuntu-beta
            system: x86_64-linux
          - os: macos-latest-xlarge
            system: aarch64-darwin
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
            accept-flake-config = true
            log-lines = 50
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: ✅ Check
        run: nix flake check --impure
      - name: 🐚 Build Shell
        run: nix build -L '.#devShells.${{ matrix.system }}.default' --impure
      - name: 📦 Build Package
        run: nix build -L '.#packages.${{ matrix.system }}.default' --impure
      - name: 🚛 Build Container
        env:
          GCLOUD_GITHUB_ACTIONS_SA: ${{ secrets.GCLOUD_GITHUB_ACTIONS_SA }}
        run: |
          nix develop . --impure -c bash -c \
            'skopeo --version && \
            echo "$GCLOUD_GITHUB_ACTIONS_SA" | skopeo login -u _json_key_base64 --password-stdin "https://europe-west3-docker.pkg.dev" && \
            nix run -L .#packages.${{ matrix.system }}.container-xhaskell-x86_64-linux.copyToRegistry --impure'
